baseurl: ""

permalink: /blog/:year/:month/:title.html

collections_dir: collections

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

google_analytics: UA-175915561-1

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
