baseurl: ""

permalink: /blog/:title.html

collections_dir: collections

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
